# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Guest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GuestWindow(object):
    def setupUi(self, GuestWindow):
        GuestWindow.setObjectName("GuestWindow")
        GuestWindow.setEnabled(True)
        GuestWindow.resize(1127, 675)
        self.centralwidget = QtWidgets.QWidget(GuestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.takeATableButton = QtWidgets.QPushButton(self.centralwidget)
        self.takeATableButton.setGeometry(QtCore.QRect(270, 240, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.takeATableButton.setFont(font)
        self.takeATableButton.setObjectName("takeATableButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 190, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tableNumLine = QtWidgets.QLineEdit(self.centralwidget)
        self.tableNumLine.setGeometry(QtCore.QRect(720, 270, 111, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.tableNumLine.setFont(font)
        self.tableNumLine.setText("")
        self.tableNumLine.setAlignment(QtCore.Qt.AlignCenter)
        self.tableNumLine.setObjectName("tableNumLine")
        self.makeCheckButton = QtWidgets.QPushButton(self.centralwidget)
        self.makeCheckButton.setGeometry(QtCore.QRect(340, 530, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.makeCheckButton.setFont(font)
        self.makeCheckButton.setObjectName("makeCheckButton")
        self.orderSumLine = QtWidgets.QLineEdit(self.centralwidget)
        self.orderSumLine.setGeometry(QtCore.QRect(50, 540, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.orderSumLine.setFont(font)
        self.orderSumLine.setText("")
        self.orderSumLine.setAlignment(QtCore.Qt.AlignCenter)
        self.orderSumLine.setReadOnly(True)
        self.orderSumLine.setObjectName("orderSumLine")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 470, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.payNLeaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.payNLeaveButton.setGeometry(QtCore.QRect(700, 530, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.payNLeaveButton.setFont(font)
        self.payNLeaveButton.setObjectName("payNLeaveButton")
        GuestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GuestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 21))
        self.menubar.setObjectName("menubar")
        GuestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GuestWindow)
        self.statusbar.setObjectName("statusbar")
        GuestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GuestWindow)
        QtCore.QMetaObject.connectSlotsByName(GuestWindow)

    def retranslateUi(self, GuestWindow):
        _translate = QtCore.QCoreApplication.translate
        GuestWindow.setWindowTitle(_translate("GuestWindow", "MainWindow"))
        self.takeATableButton.setText(_translate("GuestWindow", "Занять столик"))
        self.label_2.setText(_translate("GuestWindow", "Номер вашего стола"))
        self.makeCheckButton.setText(_translate("GuestWindow", "Попросить чек"))
        self.label_3.setText(_translate("GuestWindow", "Сумма заказа"))
        self.payNLeaveButton.setText(_translate("GuestWindow", "Заплатить и уйти"))
